### ISSUE TITLE
Crash with bigger than vanilla stack of items

### ISSUE THREAD

**Issue by Titan-Nya** [lfaoanl/MarketCrates#13]
Problem with the mod Stacker that allows altering the stack of items for bigger ones.

Then I put a bigger than vanilla stack into the crate it instantly crashed the game, the only way to get back was nbt-explorer and cheated back the deleted item into my inventory (that's why I have cheats enabled).

A possible solution for here would be to ignore any number over 64 and just count them as 64 for the render?

I know it's not your mod fault as you'd normally don't think about stacks bigger than vanilla but reporting on both sides to let know each side part of a problem they didn't know could occur.

Anyway using these crates for a temporary small container for my temporary tree farm and for my furnace array fuel storage (now more for the case I'm out of fuel).
Gonna use more of them in the village after I expend it and have all professions needed and using it as a way to remember where they are xD

**Comment by lfaoanl** [comment]
Could not recreate the bug in the new 1.19 version
