### ISSUE TITLE
[BUG] Regarding Interaction with Hoppers

### ISSUE THREAD

**Issue by JulianSharren** [lfaoanl/MarketCrates#15]
## Symptoms

1. When a hopper fails to pull an item from crates, the content of crates frantically rotates.
2. When a hopper pushes an item to a full single-deck crate, the item seemingly vanishes.

## Step to reproduce

For symptom 1:

1. place a hopper with all slots filled with some item (e.g. dirt).
2. place a crate on top of the hopper.
3. put a different item (e.g. sand) in the crate.

For symptom 2:

1. place a single-deck crate with all slots filled with some item (e.g. dirt).
2. place a hopper on the crate.
3. put a different item (e.g. sand) in the hopper.

## Note

- Symptom 1 is caused by `setChanged` method called in `AbstractCrateBlockEntity.setItem` and `AbstractCrateBlockEntity.removeItem`.  They may be removed; other components (item slots, hoppers, etc.) call it when necessary.
- Symptom 2 is caused by slots 6-11 which should only be accessible when the crate is double-decked.

**Comment by lfaoanl** [comment]
Could not reproduce symptom 1 in the new 1.19 version

Symptom 2 should now be fixed :)
